### ISSUE TITLE
Error at main.py

### ISSUE THREAD

**Issue by ghost** [frilox042/Steamgifts#1]
When I run main.py I recive this error:

```
Traceback (most recent call last):
  File "ARCHIVE LOCAL\main.py", line 1, in <module>
    from sg_requests import SgRequests
  File "ARCHIVE LOCAL\main.py", line 173
    yield from func(soup)
             ^
SyntaxError: invalid syntax
```

**Comment by ersan15** [comment]
"python3 main.py"
